# Site settings
title: "Hello, I'm Sejin Lim"
email: 'limsejin88@gmail.com'
description: "AI Engineer | Lightweight Models | End-to-End Prototyping"
baseurl: "" # 깃허브 페이지 root 사용
url: "https://IDAH-BITBOX.github.io" # 본인 깃허브 주소로 교체
twitter_username: ''
github_username: 'IDAH-BITBOX'
medium_username: ''

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

############################################################
# Pagination 설정
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'
############################################################

### Phantom settings
footer_text: '© 2025 Sejin Lim'
admin_name: 'Sejin Lim'
google_analytics: "" # 추후 Google Analytics 연결 시 채워넣기
enable_contact: true # Formspree와 연결하면 이메일 폼 활성화됨

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/projects', text: 'Projects' }
  - { url: '/blog', text: 'Blog' }
  - { url: '/contact', text: 'Contact' }

